name = "Maxnet"
uuid = "81f79f80-22f2-4e41-ab86-00c11cf0f26f"
authors = ["Tiem van der Deure <tiemvanderdeure@gmail.com>", "Michael Krabbe Borregaard <mkborregaard@sund.ku.dk>"]
version = "1.0.0-DEV"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
